[project]
name = "lazymerge-examples"
version = "0.1.0"
description = "Example notebooks for lazymerge"
requires-python = ">=3.12"
dependencies = [
    "lazymerge",
    # Visualization
    "xarray",
    "matplotlib",
    "rasterix",
    "affine",
    # DataFusion notebook
    "obstore",
    # STAC + VirtualiZarr notebook
    "boto3",
    "icechunk==1.1.21",
    "virtual-tiff",
    "zarr>=3.0,<3.2",
    "virtualizarr==2.5.0",
    "obspec-utils",
    "rasterio",
    "rasterio>=1.4.3",
    "shapely",
    "morecantile",
    "rich>=15.0.0",
    "pydot>=4.0.1",
    "cubed-xarray>=0.0.9",
    "cubed[diagnostics]>=0.27.0",
]

[tool.uv.sources]
lazymerge = { path = "../..", editable = true }
